name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  detect-changes:
    name: Detect client changes
    runs-on: ubuntu-latest
    outputs:
      changed_targets: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect path changes
        id: filter
        uses: ./.github/actions/detect_path_changes
        with:
          filters: |
            client:
              - 'client/assist-craft-dashboard/**'
              - '.github/workflows/deploy_to_s3.yml'

  deploy-s3:
    name: Deploy to S3
    needs: detect-changes
    if: needs.detect-changes.outputs.changed_targets != '[]' && needs.detect-changes.outputs.changed_targets != ''
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_CLIENT_BUCKET_NAME: ${{ secrets.S3_CLIENT_BUCKET_NAME }}
      VITE_CLERK_PUBLISHABLE_KEY: ${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }}
      VITE_CONFIG_API_BASE_URL: ${{ secrets.VITE_CONFIG_API_BASE_URL }}
      VITE_STAGE: ${{ secrets.VITE_STAGE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Node and pnpm
        uses: ./.github/actions/configure_pnpm

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install root dependencies
        run: pnpm install

      - name: Install client dependencies
        working-directory: client/assist-craft-dashboard
        run: pnpm install

      - name: Build client project
        working-directory: client/assist-craft-dashboard
        run: pnpm build

      - name: Deploy client to S3
        working-directory: client/assist-craft-dashboard
        run: pnpm run deploy-to-s3
        env:
          NODE_ENV: production
          S3_CLIENT_BUCKET_NAME: ${{ env.S3_CLIENT_BUCKET_NAME }}
          AWS_REGION: ${{ env.AWS_REGION }}
          VITE_CLERK_PUBLISHABLE_KEY: ${{ env.VITE_CLERK_PUBLISHABLE_KEY }}
          VITE_CONFIG_API_BASE_URL: ${{ env.VITE_CONFIG_API_BASE_URL }}
          VITE_STAGE: ${{ env.VITE_STAGE }}
